#!/usr/bin/env python3
"""Group the 5 per-target scenario scans into the 3-scenario comparison table."""
import json
import os

OUT = os.path.dirname(os.path.abspath(__file__))
ENG = ["kics-default", "kics-enhanced", "kubescape", "trivy", "kube-linter"]
SCEN = [
    ("raw (k8s manifests)", ["k8s"]),
    ("production (helm)", ["madgoat", "madgoat-infra"]),
    ("render-problems", ["madgoat-render", "madgoat-infra-render"]),
]
DASH = "—"


def load(n):
    d = json.load(open(os.path.join(OUT, n + ".json")))
    return {r["scanner"]: r for r in d["results"]}


data = {n: load(n) for _, ts in SCEN for n in ts}


def kord(s):
    return sorted(s, key=lambda k: int(k[1:]))


rows = []
for title, ts in SCEN:
    find = {e: sum(data[t][e]["findings"] for t in ts) for e in ENG}
    owasp = {e: kord(set().union(*[set(data[t][e]["owasp"]) for t in ts])) for e in ENG}
    rows.append((title, find, owasp))

# console
h = "{:<22}".format("scenario") + "".join("{:>14}".format(e) for e in ENG)
print("\nTABLE 1 - findings (5 engines x 3 scenarios)\n")
print(h)
print("-" * len(h))
for title, find, ow in rows:
    print("{:<22}".format(title) + "".join("{:>14}".format(find[e]) for e in ENG))
print("\nOWASP K-Top-10 (union per scenario)\n")
for title, find, ow in rows:
    print(title)
    for e in ENG:
        print("   {:<14} {}".format(e, "/".join(ow[e]) or DASH))
    print()

# markdown
with open(os.path.join(OUT, "comparison_grouped.md"), "w", encoding="utf-8") as f:
    f.write("# Five engines x three scenarios (grouped)\n\n")
    f.write("Charts per scenario: raw = `k8s/`; production = `madgoat` + `madgoat-infra`; "
            "render-problems = `madgoat-render` + `madgoat-infra-render`.\n\n")
    f.write("## Table 1 - Findings (summed per scenario)\n\n")
    f.write("| Scenario | " + " | ".join(ENG) + " |\n|---|" + "|".join(["--:"] * 5) + "|\n")
    for title, find, ow in rows:
        f.write("| " + title + " | " + " | ".join(str(find[e]) for e in ENG) + " |\n")
    f.write("\n## Table 2 - OWASP Kubernetes Top 10 (union per scenario)\n\n")
    f.write("| Scenario | " + " | ".join(ENG) + " |\n|---|" + "|".join(["---"] * 5) + "|\n")
    for title, find, ow in rows:
        f.write("| " + title + " | " + " | ".join(("/".join(ow[e]) or DASH) for e in ENG) + " |\n")

# latex
with open(os.path.join(OUT, "comparison_grouped.tex"), "w", encoding="utf-8", newline="\n") as f:
    f.write("% Generated by thesis_assets/scan_out/scenarios/group.py\n")
    f.write("\\begin{table}[htbp]\\centering\\small\n")
    f.write("\\caption{Five engines across three deployment representations of MADGoat "
            "(total findings)}\\label{tab:engine-scenarios}\n")
    f.write("\\begin{tabular}{@{}l" + "r" * 5 + "@{}}\\toprule\n")
    f.write("\\textbf{Scenario} & " + " & ".join("\\textbf{%s}" % e for e in ENG) + " \\\\\n\\midrule\n")
    for title, find, ow in rows:
        f.write(title + " & " + " & ".join(str(find[e]) for e in ENG) + " \\\\\n")
    f.write("\\bottomrule\\end{tabular}\\end{table}\n")

print("wrote comparison_grouped.md + comparison_grouped.tex")
