# Test: Helper template errors - runtime errors in _helpers.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-helper-test
data:
  # ==========================================
  # Helper template runtime error tests
  # ==========================================

  # Test: Nil pointer access in helper
  {{- if .Values.testHelperNilPointer }}
  nilPointerValue: {{ include "helpers.nilPointer" . | quote }}
  {{- end }}

  # Test: Required value missing in helper
  {{- if .Values.testHelperRequired }}
  requiredValue: {{ include "helpers.required" . | quote }}
  {{- end }}

  # Test: Range over scalar type in helper
  {{- if .Values.testHelperRangeOverScalar }}
  rangeOverScalarValue: {{ include "helpers.rangeOverScalar" . | quote }}
  {{- end }}

  # Test: Division by zero in helper
  {{- if .Values.testHelperDivZero }}
  divZeroValue: {{ include "helpers.divZero" . | quote }}
  {{- end }}

  # Test: Include non-existent template
  {{- if .Values.testHelperMissingInclude }}
  missingIncludeValue: {{ include "helpers.missingInclude" . | quote }}
  {{- end }}

  # Test: Explicit fail in helper
  {{- if .Values.testHelperExplicitFail }}
  explicitFailValue: {{ include "helpers.explicitFail" . | quote }}
  {{- end }}
