# Test: File reading errors - fails when files don't exist
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-file-test
data:
  # Fails: Glob with required match
  {{- if .Values.testGlobRequired }}
  {{- $files := .Files.Glob "files/non-existent-pattern-*.yaml" }}
  {{- if not $files }}
  error: {{ fail "No files matched the pattern" }}
  {{- end }}
  {{- end }}
  # Fails: AsConfig on empty glob result
  {{- if .Values.testAsConfigEmpty }}
  {{- $config := (.Files.Glob "missing/*.conf").AsConfig }}
  {{- if not $config }}
  error: {{ fail "No config files found" }}
  {{- end }}
  {{- end }}

