# Test: String operation errors - comprehensive testing of all string functions
{{- $testData := index .Values .Values.testDataType }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-string-test
data:
  # ==========================================
  # Print functions
  # ==========================================
  # Test: print
  {{- if .Values.testPrint }}
  printResult: {{ print $testData | quote }}
  {{- end }}
  # Test: println
  {{- if .Values.testPrintln }}
  printlnResult: {{ println $testData | quote }}
  {{- end }}
  # ==========================================
  # Printf format specifiers
  # ==========================================
  # Test: printf %s - expects string
  {{- if .Values.testPrintfString }}
  printfStringResult: {{ printf "%s-suffix" $testData | quote }}
  {{- end }}
  # Test: printf %d - expects integer
  {{- if .Values.testPrintfInt }}
  printfIntResult: {{ printf "number: %d" $testData | quote }}
  {{- end }}
  # Test: printf %f - expects float
  {{- if .Values.testPrintfFloat }}
  printfFloatResult: {{ printf "float: %f" $testData | quote }}
  {{- end }}
  # Test: printf %t - expects boolean
  {{- if .Values.testPrintfBool }}
  printfBoolResult: {{ printf "bool: %t" $testData | quote }}
  {{- end }}
  # Test: printf %x - expects integer (hex)
  {{- if .Values.testPrintfHex }}
  printfHexResult: {{ printf "hex: %x" $testData | quote }}
  {{- end }}
  # Test: printf %b - expects integer (binary)
  {{- if .Values.testPrintfBinary }}
  printfBinaryResult: {{ printf "binary: %b" $testData | quote }}
  {{- end }}
  # Test: printf %c - expects integer (character)
  {{- if .Values.testPrintfChar }}
  printfCharResult: {{ printf "char: %c" $testData | quote }}
  {{- end }}
  # Test: printf %q - expects string (quoted)
  {{- if .Values.testPrintfQuoted }}
  printfQuotedResult: {{ printf "quoted: %q" $testData | quote }}
  {{- end }}

  # ==========================================
  # Trimming functions
  # ==========================================
  # Test: trim
  {{- if .Values.testTrim }}
  trimResult: {{ trim $testData | quote }}
  {{- end }}
  # Test: trimAll
  {{- if .Values.testTrimAll }}
  trimAllResult: {{ trimAll "H" $testData | quote }}
  {{- end }}
  # Test: trimPrefix
  {{- if .Values.testTrimPrefix }}
  trimPrefixResult: {{ trimPrefix "Hello" $testData | quote }}
  {{- end }}
  # Test: trimSuffix
  {{- if .Values.testTrimSuffix }}
  trimSuffixResult: {{ trimSuffix "World" $testData | quote }}
  {{- end }}

  # ==========================================
  # Case functions
  # ==========================================
  # Test: lower
  {{- if .Values.testLower }}
  lowerResult: {{ lower $testData | quote }}
  {{- end }}
  # Test: upper
  {{- if .Values.testUpper }}
  upperResult: {{ upper $testData | quote }}
  {{- end }}
  # Test: title
  {{- if .Values.testTitle }}
  titleResult: {{ title $testData | quote }}
  {{- end }}
  # Test: untitle
  {{- if .Values.testUntitle }}
  untitleResult: {{ untitle $testData | quote }}
  {{- end }}

  # ==========================================
  # String manipulation functions
  # ==========================================
  # Test: repeat (positive)
  {{- if .Values.testRepeatPositive }}
  repeatPositiveResult: {{ repeat (int .Values.positiveInt) $testData | quote }}
  {{- end }}
  # Test: repeat (zero)
  {{- if .Values.testRepeatZero }}
  repeatZeroResult: {{ repeat (int .Values.zeroInt) $testData | quote }}
  {{- end }}
  # Test: repeat (negative)
  {{- if .Values.testRepeatNegative }}
  repeatNegativeResult: {{ repeat (int .Values.negativeInt) $testData | quote }}
  {{- end }}
  # Test: substr (positive)
  {{- if .Values.testSubstrPositive }}
  substrPositiveResult: {{ substr 0 (int .Values.positiveInt) $testData | quote }}
  {{- end }}
  # Test: substr (zero)
  {{- if .Values.testSubstrZero }}
  substrZeroResult: {{ substr 0 (int .Values.zeroInt) $testData | quote }}
  {{- end }}
  # Test: substr (negative)
  {{- if .Values.testSubstrNegative }}
  substrNegativeResult: {{ substr (int .Values.negativeInt) 0 $testData | quote }}
  {{- end }}
  # Test: nospace
  {{- if .Values.testNospace }}
  nospaceResult: {{ nospace $testData | quote }}
  {{- end }}
  # Test: trunc (positive)
  {{- if .Values.testTruncPositive }}
  truncPositiveResult: {{ trunc (int .Values.positiveInt) $testData | quote }}
  {{- end }}
  # Test: trunc (zero)
  {{- if .Values.testTruncZero }}
  truncZeroResult: {{ trunc (int .Values.zeroInt) $testData | quote }}
  {{- end }}
  # Test: trunc (negative)
  {{- if .Values.testTruncNegative }}
  truncNegativeResult: {{ trunc (int .Values.negativeInt) $testData | quote }}
  {{- end }}
  # Test: abbrev (positive)
  {{- if .Values.testAbbrevPositive }}
  abbrevPositiveResult: {{ abbrev (int .Values.positiveInt) $testData | quote }}
  {{- end }}
  # Test: abbrev (zero)
  {{- if .Values.testAbbrevZero }}
  abbrevZeroResult: {{ abbrev (int .Values.zeroInt) $testData | quote }}
  {{- end }}
  # Test: abbrev (negative)
  {{- if .Values.testAbbrevNegative }}
  abbrevNegativeResult: {{ abbrev (int .Values.negativeInt) $testData | quote }}
  {{- end }}
  # Test: abbrevboth (positive)
  {{- if .Values.testAbbrevbothPositive }}
  abbrevbothPositiveResult: {{ abbrevboth (int .Values.positiveInt) (int .Values.positiveInt) $testData | quote }}
  {{- end }}
  # Test: abbrevboth (zero)
  {{- if .Values.testAbbrevbothZero }}
  abbrevbothZeroResult: {{ abbrevboth (int .Values.zeroInt) (int .Values.zeroInt) $testData | quote }}
  {{- end }}
  # Test: abbrevboth (negative)
  {{- if .Values.testAbbrevbothNegative }}
  abbrevbothNegativeResult: {{ abbrevboth (int .Values.negativeInt) (int .Values.negativeInt) $testData | quote }}
  {{- end }}
  # Test: initials
  {{- if .Values.testInitials }}
  initialsResult: {{ initials $testData | quote }}
  {{- end }}

  # ==========================================
  # Random string functions
  # ==========================================
  # Test: randAlphaNum (positive)
  {{- if .Values.testRandAlphaNumPositive }}
  randAlphaNumPositiveResult: {{ randAlphaNum (int .Values.positiveInt) | quote }}
  {{- end }}
  # Test: randAlphaNum (zero)
  {{- if .Values.testRandAlphaNumZero }}
  randAlphaNumZeroResult: {{ randAlphaNum (int .Values.zeroInt) | quote }}
  {{- end }}
  # Test: randAlphaNum (negative)
  {{- if .Values.testRandAlphaNumNegative }}
  randAlphaNumNegativeResult: {{ randAlphaNum (int .Values.negativeInt) | quote }}
  {{- end }}
  # Test: randAlpha (positive)
  {{- if .Values.testRandAlphaPositive }}
  randAlphaPositiveResult: {{ randAlpha (int .Values.positiveInt) | quote }}
  {{- end }}
  # Test: randAlpha (zero)
  {{- if .Values.testRandAlphaZero }}
  randAlphaZeroResult: {{ randAlpha (int .Values.zeroInt) | quote }}
  {{- end }}
  # Test: randAlpha (negative)
  {{- if .Values.testRandAlphaNegative }}
  randAlphaNegativeResult: {{ randAlpha (int .Values.negativeInt) | quote }}
  {{- end }}
  # Test: randNumeric (positive)
  {{- if .Values.testRandNumericPositive }}
  randNumericPositiveResult: {{ randNumeric (int .Values.positiveInt) | quote }}
  {{- end }}
  # Test: randNumeric (zero)
  {{- if .Values.testRandNumericZero }}
  randNumericZeroResult: {{ randNumeric (int .Values.zeroInt) | quote }}
  {{- end }}
  # Test: randNumeric (negative)
  {{- if .Values.testRandNumericNegative }}
  randNumericNegativeResult: {{ randNumeric (int .Values.negativeInt) | quote }}
  {{- end }}
  # Test: randAscii (positive)
  {{- if .Values.testRandAsciiPositive }}
  randAsciiPositiveResult: {{ randAscii (int .Values.positiveInt) | quote }}
  {{- end }}
  # Test: randAscii (zero)
  {{- if .Values.testRandAsciiZero }}
  randAsciiZeroResult: {{ randAscii (int .Values.zeroInt) | quote }}
  {{- end }}
  # Test: randAscii (negative)
  {{- if .Values.testRandAsciiNegative }}
  randAsciiNegativeResult: {{ randAscii (int .Values.negativeInt) | quote }}
  {{- end }}

  # ==========================================
  # Wrap functions
  # ==========================================
  # Test: wrap (positive)
  {{- if .Values.testWrapPositive }}
  wrapPositiveResult: {{ wrap (int .Values.positiveInt) $testData | quote }}
  {{- end }}
  # Test: wrap (zero)
  {{- if .Values.testWrapZero }}
  wrapZeroResult: {{ wrap (int .Values.zeroInt) $testData | quote }}
  {{- end }}
  # Test: wrap (negative)
  {{- if .Values.testWrapNegative }}
  wrapNegativeResult: {{ wrap (int .Values.negativeInt) $testData | quote }}
  {{- end }}
  # Test: wrapWith (positive)
  {{- if .Values.testWrapWithPositive }}
  wrapWithPositiveResult: {{ wrapWith (int .Values.positiveInt) "\n" $testData | quote }}
  {{- end }}
  # Test: wrapWith (zero)
  {{- if .Values.testWrapWithZero }}
  wrapWithZeroResult: {{ wrapWith (int .Values.zeroInt) "\n" $testData | quote }}
  {{- end }}
  # Test: wrapWith (negative)
  {{- if .Values.testWrapWithNegative }}
  wrapWithNegativeResult: {{ wrapWith (int .Values.negativeInt) "\n" $testData | quote }}
  {{- end }}

  # ==========================================
  # Search/match functions
  # ==========================================
  # Test: contains
  {{- if .Values.testContains }}
  containsResult: {{ contains "test" $testData | quote }}
  {{- end }}
  # Test: hasPrefix
  {{- if .Values.testHasPrefix }}
  hasPrefixResult: {{ hasPrefix "Hello" $testData | quote }}
  {{- end }}
  # Test: hasSuffix
  {{- if .Values.testHasSuffix }}
  hasSuffixResult: {{ hasSuffix "World" $testData | quote }}
  {{- end }}

  # ==========================================
  # Quoting functions
  # ==========================================
  # Test: quote
  {{- if .Values.testQuote }}
  quoteResult: {{ quote $testData }}
  {{- end }}
  # Test: squote
  {{- if .Values.testSquote }}
  squoteResult: {{ squote $testData }}
  {{- end }}

  # ==========================================
  # Concatenation
  # ==========================================
  # Test: cat
  {{- if .Values.testCat }}
  catResult: {{ cat $testData "suffix" | quote }}
  {{- end }}

  # ==========================================
  # Indentation functions
  # ==========================================
  # Test: indent (positive)
  {{- if .Values.testIndentPositive }}
  indentPositiveResult: {{ indent (int .Values.positiveInt) $testData | quote }}
  {{- end }}
  # Test: indent (zero)
  {{- if .Values.testIndentZero }}
  indentZeroResult: {{ indent (int .Values.zeroInt) $testData | quote }}
  {{- end }}
  # Test: indent (negative)
  {{- if .Values.testIndentNegative }}
  indentNegativeResult: {{ indent (int .Values.negativeInt) $testData | quote }}
  {{- end }}
  # Test: nindent (positive)
  {{- if .Values.testNindentPositive }}
  nindentPositiveResult: {{ nindent (int .Values.positiveInt) $testData | quote }}
  {{- end }}
  # Test: nindent (zero)
  {{- if .Values.testNindentZero }}
  nindentZeroResult: {{ nindent (int .Values.zeroInt) $testData | quote }}
  {{- end }}
  # Test: nindent (negative)
  {{- if .Values.testNindentNegative }}
  nindentNegativeResult: {{ nindent (int .Values.negativeInt) $testData | quote }}
  {{- end }}

  # ==========================================
  # Replacement
  # ==========================================
  # Test: replace
  {{- if .Values.testReplace }}
  replaceResult: {{ replace "Hello" "Hi" $testData | quote }}
  {{- end }}

  # ==========================================
  # Pluralization
  # ==========================================
  # Test: plural (positive)
  {{- if .Values.testPluralPositive }}
  pluralPositiveResult: {{ plural "item" "items" (int .Values.positiveInt) | quote }}
  {{- end }}
  # Test: plural (zero)
  {{- if .Values.testPluralZero }}
  pluralZeroResult: {{ plural "item" "items" (int .Values.zeroInt) | quote }}
  {{- end }}
  # Test: plural (negative)
  {{- if .Values.testPluralNegative }}
  pluralNegativeResult: {{ plural "item" "items" (int .Values.negativeInt) | quote }}
  {{- end }}

  # ==========================================
  # Case conversion functions
  # ==========================================
  # Test: snakecase
  {{- if .Values.testSnakecase }}
  snakecaseResult: {{ snakecase $testData | quote }}
  {{- end }}
  # Test: camelcase
  {{- if .Values.testCamelcase }}
  camelcaseResult: {{ camelcase $testData | quote }}
  {{- end }}
  # Test: kebabcase
  {{- if .Values.testKebabcase }}
  kebabcaseResult: {{ kebabcase $testData | quote }}
  {{- end }}
  # Test: swapcase
  {{- if .Values.testSwapcase }}
  swapcaseResult: {{ swapcase $testData | quote }}
  {{- end }}

  # ==========================================
  # Shuffle
  # ==========================================
  # Test: shuffle
  {{- if .Values.testShuffle }}
  shuffleResult: {{ shuffle $testData | quote }}
  {{- end }}

  # ==========================================
  # Type conversion functions
  # ==========================================
  # Test: atoi
  {{- if .Values.testAtoi }}
  atoiResult: {{ atoi $testData }}
  {{- end }}
  # Test: int64
  {{- if .Values.testInt64 }}
  int64Result: {{ int64 $testData }}
  {{- end }}
  # Test: float64
  {{- if .Values.testFloat64 }}
  float64Result: {{ float64 $testData }}
  {{- end }}

