package config

import "flag"

const (
	modeFlag           = "mode"
	modeUsage          = "Execution mode: full, github-search-json, or artifacthub-search-json"
	modeDefault        = "full"
	sourceFlag         = "source"
	sourceUsage        = "Discovery source: artifacthub or github (full mode loads repos from -search-in JSON)"
	sourceDefault      = "artifacthub"
	topFlag            = "top"
	topUsage           = "Top N repositories to inspect from -search-in JSON in full mode"
	topDefault         = 400
	pageSizeFlag       = "page-size"
	pageSizeUsage      = "Results per API request/page (artifacthub max 60, github max 100)"
	pageSizeDefault    = 60
	searchTopFlag      = "search-top"
	searchTopUsage     = "In *-search-json modes, number of repos to include in output"
	searchTopDefault   = 1000
	searchOrderFlag    = "search-order"
	searchOrderUsage   = "In github-search-json mode, star ordering: desc or asc"
	searchOrderDefault = "desc"
	searchInFlag       = "search-in"
	searchInUsage      = "In full mode, input JSON file generated by github-search-json or artifacthub-search-json mode"
	searchInDefault    = "github_search.json"
	searchOutFlag      = "search-out"
	searchOutUsage     = "In *-search-json modes, output JSON file path"
	searchOutDefault   = "github_search.json"
	cloneDirFlag       = "clone-dir"
	cloneDirUsage      = "Directory where repositories are cloned"
	cloneDirDefault    = "cloned"
)

// Config groups all runtime settings parsed from CLI flags.
type Config struct {
	Mode        string
	Source      string
	Top         int
	PageSize    int
	SearchTop   int
	SearchOrder string
	SearchIn    string
	SearchOut   string
	CloneDir    string
}

func Parse() Config {
	mode := flag.String(modeFlag, modeDefault, modeUsage)
	source := flag.String(sourceFlag, sourceDefault, sourceUsage)
	top := flag.Int(topFlag, topDefault, topUsage)
	pageSize := flag.Int(pageSizeFlag, pageSizeDefault, pageSizeUsage)
	searchTop := flag.Int(searchTopFlag, searchTopDefault, searchTopUsage)
	searchOrder := flag.String(searchOrderFlag, searchOrderDefault, searchOrderUsage)
	searchIn := flag.String(searchInFlag, searchInDefault, searchInUsage)
	searchOut := flag.String(searchOutFlag, searchOutDefault, searchOutUsage)
	cloneDir := flag.String(cloneDirFlag, cloneDirDefault, cloneDirUsage)
	flag.Parse()

	return Config{
		Mode:        *mode,
		Source:      *source,
		Top:         *top,
		PageSize:    *pageSize,
		SearchTop:   *searchTop,
		SearchOrder: *searchOrder,
		SearchIn:    *searchIn,
		SearchOut:   *searchOut,
		CloneDir:    *cloneDir,
	}
}
