apiVersion: v2
name: test-global-values
description: Test chart for global values override behavior
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: child
    version: "0.1.0"
    repository: ""
