# Test: Regex operation errors - comprehensive testing of all regex functions
{{- $testData := index .Values .Values.testDataType }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-regex-test
data:
  # ==========================================
  # Match functions
  # ==========================================
  # Test: regexMatch
  {{- if .Values.testRegexMatch }}
  regexMatch: {{ regexMatch .Values.validPattern $testData | quote }}
  {{- end }}
  # Test: mustRegexMatch
  {{- if .Values.testMustRegexMatch }}
  mustRegexMatch: {{ mustRegexMatch .Values.validPattern $testData | quote }}
  {{- end }}

  # ==========================================
  # Find functions
  # ==========================================
  # Test: regexFindAll
  {{- if .Values.testRegexFindAll }}
  regexFindAll: {{ regexFindAll .Values.validPattern $testData -1 | toJson }}
  {{- end }}
  # Test: mustRegexFindAll
  {{- if .Values.testMustRegexFindAll }}
  mustRegexFindAll: {{ mustRegexFindAll .Values.validPattern $testData -1 | toJson }}
  {{- end }}
  # Test: regexFind
  {{- if .Values.testRegexFind }}
  regexFind: {{ regexFind .Values.validPattern $testData | quote }}
  {{- end }}
  # Test: mustRegexFind
  {{- if .Values.testMustRegexFind }}
  mustRegexFind: {{ mustRegexFind .Values.validPattern $testData | quote }}
  {{- end }}

  # ==========================================
  # Replace functions
  # ==========================================
  # Test: regexReplaceAll
  {{- if .Values.testRegexReplaceAll }}
  regexReplaceAll: {{ regexReplaceAll .Values.validPattern .Values.replacement $testData | quote }}
  {{- end }}
  # Test: mustRegexReplaceAll
  {{- if .Values.testMustRegexReplaceAll }}
  mustRegexReplaceAll: {{ mustRegexReplaceAll .Values.validPattern .Values.replacement $testData | quote }}
  {{- end }}
  # Test: regexReplaceAllLiteral
  {{- if .Values.testRegexReplaceAllLiteral }}
  regexReplaceAllLiteral: {{ regexReplaceAllLiteral .Values.validPattern .Values.replacement $testData | quote }}
  {{- end }}
  # Test: mustRegexReplaceAllLiteral
  {{- if .Values.testMustRegexReplaceAllLiteral }}
  mustRegexReplaceAllLiteral: {{ mustRegexReplaceAllLiteral .Values.validPattern .Values.replacement $testData | quote }}
  {{- end }}

  # ==========================================
  # Split functions
  # ==========================================
  # Test: regexSplit
  {{- if .Values.testRegexSplit }}
  regexSplit: {{ regexSplit .Values.validPattern $testData -1 | toJson }}
  {{- end }}
  # Test: mustRegexSplit
  {{- if .Values.testMustRegexSplit }}
  mustRegexSplit: {{ mustRegexSplit .Values.validPattern $testData -1 | toJson }}
  {{- end }}

