# Test: tpl function errors - runtime errors in tpl function calls
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tpl-test
data:
  # ==========================================
  # tpl function error tests
  # ==========================================

  # Test: Syntax error in tpl string (unclosed action)
  {{- if .Values.testTplSyntaxError }}
  syntaxErrorValue: {{ tpl .Values.tplSyntaxError . | quote }}
  {{- end }}

  # Test: Nil pointer in tpl string
  {{- if .Values.testTplNilPointer }}
  nilPointerValue: {{ tpl .Values.tplNilPointer . | quote }}
  {{- end }}

  # Test: Required value missing in tpl string
  {{- if .Values.testTplRequired }}
  requiredValue: {{ tpl .Values.tplRequired . | quote }}
  {{- end }}

  # Test: Division by zero in tpl string
  {{- if .Values.testTplDivZero }}
  divZeroValue: {{ tpl .Values.tplDivZero . | quote }}
  {{- end }}

  # Test: Type mismatch (range over scalar) in tpl string
  {{- if .Values.testTplTypeMismatch }}
  typeMismatchValue: {{ tpl .Values.tplTypeMismatch . | quote }}
  {{- end }}

  # Test: Invalid function in tpl string
  {{- if .Values.testTplInvalidFunc }}
  invalidFuncValue: {{ tpl .Values.tplInvalidFunc . | quote }}
  {{- end }}

  # Test: Explicit fail in tpl string
  {{- if .Values.testTplFail }}
  failValue: {{ tpl .Values.tplFail . | quote }}
  {{- end }}
