# Test: File and path function errors - comprehensive testing
{{- $testData := index .Values .Values.testDataType }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-file-path-test
data:
  # ==========================================
  # Path functions
  # ==========================================
  # Test: base - returns the last element of path
  {{- if .Values.testBase }}
  baseValue: {{ base $testData | quote }}
  {{- end }}
  # Test: dir - returns all but the last element of path
  {{- if .Values.testDir }}
  dirValue: {{ dir $testData | quote }}
  {{- end }}
  # Test: clean - cleans up a path
  {{- if .Values.testClean }}
  cleanValue: {{ clean $testData | quote }}
  {{- end }}
  # Test: ext - returns the file extension
  {{- if .Values.testExt }}
  extValue: {{ ext $testData | quote }}
  {{- end }}
  # Test: isAbs - checks if path is absolute
  {{- if .Values.testIsAbs }}
  isAbsValue: {{ isAbs $testData | quote }}
  {{- end }}

  # ==========================================
  # File functions
  # ==========================================
  # Test: Glob with required match
  {{- if .Values.testGlobRequired }}
  {{- $files := .Files.Glob $testData }}
  {{- if not $files }}
  error: {{ fail "No files matched the pattern" }}
  {{- end }}
  {{- end }}
  # Test: AsConfig on empty glob result
  {{- if .Values.testAsConfigEmpty }}
  {{- $config := (.Files.Glob $testData).AsConfig }}
  {{- if not $config }}
  error: {{ fail "No config files found" }}
  {{- end }}
  {{- end }}

  # ==========================================
  # Advanced Files operations (merged from test-16)
  # ==========================================
  # Test: Required file content that doesn't exist
  {{- if .Values.testFilesMissingRequired }}
  missingContent: {{ required "File content is required" (.Files.Get "non-existent-file.txt") | quote }}
  {{- end }}

  # Test: Required file bytes that doesn't exist
  {{- if .Values.testFilesEmptyRequired }}
  {{- $bytes := .Files.GetBytes "another-missing-file.bin" }}
  emptyBytes: {{ required "File bytes are required" $bytes | b64enc | quote }}
  {{- end }}

  # Test: Nil path passed to Files.Get
  {{- if .Values.testFilesNilPath }}
  {{- $content := .Files.Get .Values.nilFilePath }}
  nilPathValue: {{ required "File path cannot be nil" $content | quote }}
  {{- end }}

  # Test: Template error in file content processed with tpl
  {{- if .Values.testFilesTplError }}
  tplErrorValue: {{ tpl .Values.tplErrorContent . | quote }}
  {{- end }}

