# Test: List operation errors - comprehensive testing of all list functions
{{- $testData := index .Values .Values.testDataType }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-list-test
data:
  # ==========================================
  # First/Last functions
  # ==========================================
  # Test: first
  {{- if .Values.testFirst }}
  firstItem: {{ first $testData | quote }}
  {{- end }}
  # Test: mustFirst
  {{- if .Values.testMustFirst }}
  mustFirstItem: {{ mustFirst $testData | quote }}
  {{- end }}
  # Test: rest
  {{- if .Values.testRest }}
  restItems: {{ rest $testData | toJson }}
  {{- end }}
  # Test: mustRest
  {{- if .Values.testMustRest }}
  mustRestItems: {{ mustRest $testData | toJson }}
  {{- end }}
  # Test: last
  {{- if .Values.testLast }}
  lastItem: {{ last $testData | quote }}
  {{- end }}
  # Test: mustLast
  {{- if .Values.testMustLast }}
  mustLastItem: {{ mustLast $testData | quote }}
  {{- end }}
  # Test: initial
  {{- if .Values.testInitial }}
  initialItems: {{ initial $testData | toJson }}
  {{- end }}
  # Test: mustInitial
  {{- if .Values.testMustInitial }}
  mustInitialItems: {{ mustInitial $testData | toJson }}
  {{- end }}

  # ==========================================
  # Append/Prepend functions
  # ==========================================
  # Test: append
  {{- if .Values.testAppend }}
  appendedList: {{ append $testData "item" | toJson }}
  {{- end }}
  # Test: mustAppend
  {{- if .Values.testMustAppend }}
  mustAppendedList: {{ mustAppend $testData "item" | toJson }}
  {{- end }}
  # Test: prepend
  {{- if .Values.testPrepend }}
  prependedList: {{ prepend $testData "item" | toJson }}
  {{- end }}
  # Test: mustPrepend
  {{- if .Values.testMustPrepend }}
  mustPrependedList: {{ mustPrepend $testData "item" | toJson }}
  {{- end }}

  # ==========================================
  # List manipulation functions
  # ==========================================
  # Test: concat
  {{- if .Values.testConcat }}
  concatenatedList: {{ concat .Values.validList $testData | toJson }}
  {{- end }}
  # Test: reverse
  {{- if .Values.testReverse }}
  reversedList: {{ reverse $testData | toJson }}
  {{- end }}
  # Test: mustReverse
  {{- if .Values.testMustReverse }}
  mustReversedList: {{ mustReverse $testData | toJson }}
  {{- end }}
  # Test: uniq
  {{- if .Values.testUniq }}
  uniqueList: {{ uniq $testData | toJson }}
  {{- end }}
  # Test: mustUniq
  {{- if .Values.testMustUniq }}
  mustUniqueList: {{ mustUniq $testData | toJson }}
  {{- end }}

  # ==========================================
  # Search/Filter functions
  # ==========================================
  # Test: without
  {{- if .Values.testWithout }}
  withoutList: {{ without $testData "item" | toJson }}
  {{- end }}
  # Test: mustWithout
  {{- if .Values.testMustWithout }}
  mustWithoutList: {{ mustWithout $testData "item" | toJson }}
  {{- end }}
  # Test: has
  {{- if .Values.testHas }}
  hasList: {{ has "item" $testData | quote }}
  {{- end }}
  # Test: mustHas
  {{- if .Values.testMustHas }}
  mustHasList: {{ mustHas "item" $testData | quote }}
  {{- end }}
  # Test: compact
  {{- if .Values.testCompact }}
  compactList: {{ compact $testData | toJson }}
  {{- end }}
  # Test: mustCompact
  {{- if .Values.testMustCompact }}
  mustCompactList: {{ mustCompact $testData | toJson }}
  {{- end }}

  # ==========================================
  # Index/Slice functions
  # ==========================================
  # Test: index
  {{- if .Values.testIndex }}
  indexedItem: {{ index $testData 0 | quote }}
  {{- end }}
  # Test: slice
  {{- if .Values.testSlice }}
  slicedList: {{ slice $testData 0 1 | toJson }}
  {{- end }}
  # Test: mustSlice
  {{- if .Values.testMustSlice }}
  mustSlicedList: {{ mustSlice $testData 0 1 | toJson }}
  {{- end }}

  # ==========================================
  # Range/Sequence functions
  # ==========================================
  # Test: until
  {{- if .Values.testUntil }}
  untilList: {{ until $testData | toJson }}
  {{- end }}
  # Test: untilStep
  {{- if .Values.testUntilStep }}
  untilStepList: {{ untilStep $testData 10 1 | toJson }}
  {{- end }}
  # Test: seq
  {{- if .Values.testSeq }}
  seqList: {{ seq $testData | toJson }}
  {{- end }}
  # Test: chunk
  {{- if .Values.testChunk }}
  chunkedList: {{ chunk $testData .Values.validList | toJson }}
  {{- end }}
